config.js, index.js, test/api.js, test/cli.js, test/rules.js
This fixes most of the errors from test failures I can reproduce locally (in issue #15), but then I encountered a bunch of issues with the paths to the test fixtures and the `execa.stdout` calls. Something seems up. Any ideas?
Stacktrace
<details>
<pre><code>% npm test                                 /opt/awesome-lint (fix-local-errors)
> awesome-lint@0.1.0 test /opt/awesome-lint
> xo && ava
4 failed
api › main
/opt/awesome-lint/index.js:18
17:   if (!readmeFile) {                                                     
18:     return Promise.reject(new Error(`Couldn't find the file ${opts.filen…
19:   }                                                                      
Rejected promise returned by test
Rejection reason:
[Error: Couldn't find the file fixtures/main.md]
m (index.js:18:25) …
=> Fix test errors from linting issues - fixes #15

package.json
This was just missing previously.
We should probably also bump awesome-lint version after this.
=> Add `lib` directory to `files` field in package.json

cli.js, index.js, package.json, readme.md, test/api.js
I currently am trying to add CI to ```sindresorhus/awesome``` using Azure Pipelines, and I would like to use a custom reporter so that I can display test results in the Pipelines test UI. This PR enables that by adding support for custom reporters.
PR here: https://github.com/sindresorhus/awesome/pull/1505
=> Add `reporter` option

rules/license.js, rules/toc.js
Add accepting British spelling of '[Licence](https://dictionary.cambridge.org/dictionary/english/licence)' (spelt with -ce) as a correct spelling in the License and TOC rules
=> Allow British spelling of 'Licence'

rules/list-item.js, test/fixtures/list-item/0.md
Fixes #52.
Upper case should be also considered as valid. And I added those 2 cases into tests.
=> Consider upper as valid list item prefix case

package.json, rules/heading.js, rules/index.js, test/fixtures/heading/error0.md, test/fixtures/heading/error1.md, test/fixtures/heading/error2.md, test/fixtures/heading/error3.md, test/fixtures/heading/success0.md, test/fixtures/heading/success1.md, test/rules/heading.js
The `awesome/heading` rule lints all of the given file's headings, verifying that:
- There is exactly one heading.
- It's in title case.
- It's children array is flat (i.e. it doesn't have any nested and complicated child elements).
Fixes #59
=> Add rule awesome/heading

rules/git-repo-age.js, test/rules/git-repo-age.js
The "Awesome list must reside in a valid git repository" error message
(awesome/git-repo-age) also appears when (e.g. Travis) makes a shallow
copy of the awesome repo.  This is documented in the README file, but
users may miss it.  Rephrase error message and add a pointer to the
README file.
=> Improve awesome/git-repo-age error message

readme.md, rules/github.js, test/rules/github.js
=> Add GitHub API rate limit alert

rules/github.js, test/rules/github.js
Resolve/Get Git url with the comand: `git remote get-url --push origin`
Fixes #86
=> Git remote URL can be shorthand

rules/contributing.js
[Like `code-of-conduct.md` file](https://github.com/sindresorhus/awesome-lint/commit/ddbebd140ae6a11d193c55d84889cbf93f9bb747#diff-168726dbe96b3ce427e7fedce31bb0bcR38), `contribution.md` is allowed to be placed in the `.github` subfolder of a repository.
> To help your project contributors do good work, you can add a file with contribution guidelines to your project repository's root, `docs`, or `.github` folder. 
Source: https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors
=> Allow `.github` directory to contain contribution guidelines

index.js, rules/contributing.js, test/fixtures/contributing/valid2/.github/CONTRIBUTING.md, test/fixtures/contributing/valid3/.github/contributing.md, test/rules/contributing.js
This PR fix the use of optional folder glob pattern to locate contribution and code of conduct guidelines. Also adds fixtures and unittests.
=> Fix location matching of contributing.md and code-of-conduct.md files

rules/toc.js, test/fixtures/toc/0.md, test/fixtures/toc/1.md, test/fixtures/toc/2.md, test/fixtures/toc/3.md, test/fixtures/toc/4.md, test/fixtures/toc/5.md
That way we can group non-important but necessary content (like extra-copyright notices, hyperlinks to sources, pointers to expansive content, ...) at the end of the document while keeping the main content hyper-focused to our curated awesome lists.
Fixes #117 .
Real-life example available on the `Awesome Falsehood` project at: https://github.com/kdeldycke/awesome-falsehood/blob/d8db15ad0c6b0acaea1e6da1f48ea4a5922d4118/readme.md#footnotes
=> Allow for a Footnotes section at the end of an Awesome list

package.json
`is-url-superb` package prior to version 4 used a vulnerability package `url-regex` (https://www.npmjs.com/advisories/1550).
Version 4 drops the dependency and makes audit happy again 👍
=> Update is-url-superb package to ^4.0.0

rules/index.js, rules/license.js, rules/toc.js, test/fixtures/license/error0.md, test/fixtures/license/error2.md, test/fixtures/license/error3.md, test/fixtures/license/error4.md, test/fixtures/license/success0.md, test/fixtures/toc/0.md, test/fixtures/toc/1.md, test/fixtures/toc/2.md, test/fixtures/toc/3.md, test/fixtures/toc/4.md, test/fixtures/toc/5.md, test/rules/license.js
This PR backports and enforces new rules discussed with @sindresorhus in https://github.com/sindresorhus/awesome/pull/1860 :
1. Force the optional contribution section to be named `Contributing`. `Contribute` is no longer allowed, as per https://github.com/sindresorhus/awesome/pull/1860#discussion_r496219219
2. Forbid `Licence` or `License` section. The preferred method is to rely on GitHub's license detection. See https://github.com/sindresorhus/awesome/pull/1860#discussion_r496217532
This PR related to:
* https://github.com/sindresorhus/awesome-lint/issues/93
* https://github.com/sindresorhus/awesome-lint/issues/91
=> Forbid License, Licence and Contribute sections

test/fixtures/list-item/0.md
Closed #44.
The main work is done in remark side. Just follow https://github.com/sindresorhus/awesome-lint/issues/44#issuecomment-616087986 to check. Looks good.
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#44: Fix support for tabbed sub-lists](https://issuehunt.io/repos/64659785/issues/44)
---
</details>
=> Uncomment tests of tabbed/mixed list items

rules/list-item.js, test/fixtures/list-item/0.md
=> Allow using emphasis text style in link title

rules/spell-check.js, test/fixtures/spell-check/success0.md
Remove URL segments from input values to skip them during validation. 
Closes #71
Closes #132
=> Skip URLs in spell check rule

readme.md
Using npx removes the need to install the package globally, and ensures that every usage will be up to date.
Closes #138
=> Use npx in readme usage instructions

.github/workflows/main.yml, .gitmodules, test/integration.js
Closes #75
I'm using submodules to create local copies of repos to lint using the awesome-lint CLI. I've used repos from sindresorhus as others listed in #75 end up with hundreds of lint errors.
The test runs the CLI on a submodule and checks that all the errors are expected. A repo with no errors would use `t.notThrowsAsync` instead.
=> Add integration test using some canonical lists

rules/list-item.js
Fixes #153.
This PR fixes the errors that appear when having apostrophes or interpuncts in the first word of the description. Examples that produced an error but now pass:
````
- [GPT-3](https://openai.com/api/) - OpenAI's API provides access to GPT-3, which performs a wide variety of natural language tasks, and Codex, which translates natural language to code.
- [DALL·E 2](https://openai.com/dall-e-2/) - DALL·E 2 by OpenAI is a new AI system that can create realistic images and art from a description in natural language.
````
=> Allow apostrophe and interpunct in first word of item description

rules/list-item.js, test/fixtures/list-item/0.md
Fixes #148 
I would like to propose adding the apostrophe symbol for word tokenization, so that the linter does not complain on possessive forms.
The integration tests don't run locally for me (due to missing API access, happy to help fix that if someone can guide me). The local tests after my addition appear unchanged (no additional failures):
```
6 warnings
9 tests failed
2 known failures
rules › code-of-conduct › code-of-conduct - invalid if has placeholder
rules › code-of-conduct › code-of-conduct - invalid if just copied
```
In order to clearly separate the added test from the tokenization change, I have _not_ squashed local commits. Apologies if this PR does violate the Contribution Guidelines for that. I'm happy to help in the future and happy to learn from this issue to submit …
=> Add apostrophe to word tokenization list allowing possessive forms

rules/github.js
The rule `remark-lint:awesome-github` has false negatives when the remote name is `origin`. More detail in the linked issue.
Closes #169
=> Do not assume remote name is `origin` in `remark-lint:awesome-github`

rules/github.js
From [this comment](https://github.com/sindresorhus/awesome-lint/issues/172#issuecomment-1732057902) in the referrenced issue:
> This broke linting because the code did not take into account that HEAD may not point to a branch - it could be in a detached state. And this commonly occurs in Github Actions when @actions/checkout is used to clone a repository.
If we are not currently in a branch, then we:
- Infer remote name from the config key `clone.defaultRemoteName`
- If that config key is not set, then the value is defaulted to 'origin' (the original default)
These fixes were tested in [this PR](https://github.com/fox-forks/awesome-google-cloud/pull/1) (and [this PR](https://github.com/fox-forks/awesome-google-cloud/pull/2)), which had CI config like:
```yaml
jobs:
awesome-lint:
steps:
- …
```
=> fix: If remote cannot be inferred, default to config `clone.defaultRemoteName`, then `origin`

rules/list-item.js, rules/toc.js
Given an Awesome Markdown file that includes the following:
```md
...
- [Official](#official)
- [Instances](#instances)
- [Statistics](#statistics)
- [People](#people)
- [Tools](#tools)
...
```
Linting fails because of the `` comment.
```sh
$ pnpx awesome-lint
✖ Linting
README.md:11:3
✖   1:1  Missing or invalid Table of Contents  remark-lint:awesome-toc
✖  11:3  Invalid list item link URL            remark-lint:awesome-list-item
✖  12:3  Invalid list item link URL            remark-lint:awesome-list-item
✖  13:3  Invalid list item link URL            remark-lint:awesome-list-item
✖  14:3  Invalid list item link URL            remark-lint:awesome-list-item
✖  15:3  Invalid list item link URL            remark-lint:awesome-list-item
✖  16:3  Invalid list item link URL …
```
=> fix: Properly detect 'Contents' header if it includes an HTML comment

lib/find-readme-file.js
The default `readme` regexp is very liberal. So much so, it captures vim swap files for me. Is it reasonable to require the filename not have extra characters before or after the matching pattern?
I can imagine forcing `^` could be to strict if filename includes additional path information. but I think `$` should always be reasonable. (and would avoid any vim `.swp`.
And maybe it's entirely unnecessary. I can specify `readme.md` as a CLI argument if i'm worried about swap files.
=> FIX: avoid temp files like .readme.md.swp

readme.md
When I was setting up `awesome-lint` for an awesome list I am working on, I noticed the example checkout code action was using an older version. This pull request updates the sample code for a GitHub action from v2 -> v4. Thanks!
=> Update example GH action
